version: '3'

services:
  #
  # janus-gateway
  janus-gateway:
    image: canyan/janus-gateway:0.10.7
    command: ["/usr/local/bin/janus", "-F", "/usr/local/etc/janus"]
    ports:
      - "${EXPOSE_IP}:8088:8088" # http
      - "${EXPOSE_IP}:8089:8089" # https
      - "${EXPOSE_IP}:8188:8188" # ws
      - "${EXPOSE_IP}:8989:8989" # wss
      - "${EXPOSE_IP}:8000:8000"
      - "${EXPOSE_IP}:7088:7088" # http admin
      - "${EXPOSE_IP}:7889:7889" # https admin
    volumes:
      - ./docker-containers/ssl-certs:/usr/local/etc/ssl-certs
      - ./docker-containers/janus/janus.jcfg:/usr/local/etc/janus/janus.jcfg
      - ./docker-containers/janus/janus.eventhandler.sampleevh.jcfg:/usr/local/etc/janus/janus.eventhandler.sampleevh.jcfg
      - ./docker-containers/janus/janus.transport.http.jcfg:/usr/local/etc/janus/janus.transport.http.jcfg
      - ./docker-containers/janus/janus.transport.websockets.jcfg:/usr/local/etc/janus/janus.transport.websockets.jcfg
      - ./docker-logs/janus/log:/var/log
  #
  # nginx for demo apps
  nginx:
    image: nginx:1.21-alpine
    ports:
      - "${EXPOSE_IP}:80:80"
      - "${EXPOSE_IP}:443:443"
    environment:
      - DEMO_DOMAIN
      - WORK_DOMAIN
    volumes:
      - "./janus-gateway/html:/usr/src/${DEMO_DOMAIN}" # demos
      - "./work:/usr/src/${WORK_DOMAIN}" # work
      - "./janus-gateway/html/janus.js:/usr/src/${WORK_DOMAIN}/js/janus.js:ro" # js api for work
      - ./docker-containers/ssl-certs:/etc/nginx/deploy/ssl-certs
      - ./docker-containers/nginx/templates:/etc/nginx/templates
      - ./docker-logs/nginx/log:/var/log/nginx
